<a href="https://colab.research.google.com/github/arthineruturi/ML/blob/main/Lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY ARRAYS**


In [ ]:
import numpy as np 

a=np.array([1,2,3])
print(a.shape)
print(type(a))
print(a[0],a[1],a[2])
a[0]=4
print(a)

print("\n")

b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(type(b))
print(b[1,0])
print(b)

(3,)
<class 'numpy.ndarray'>
1 2 3
[4 2 3]


(2, 3)
<class 'numpy.ndarray'>
4
[[1 2 3]
 [4 5 6]]
